config:
  withdraw.reusetimer: 10
  withdraw.minimum: 100.00
language:
  color.character: "&"
  color.warning: "&4"
  color.info: "&2"
  message.prefix: "&e[&2PaperMoney&e] "
  message.warning.wrongitem: "Not a valid bank note."
  message.warning.wrongcommandusage: "Incorrect Command Usage."
  message.warning.withdrawusage: "Usage:&r /withdraw [amount]"
  message.warning.giveusage: "Usage:&r /papermoney give [amount]"
  message.warning.papermoneyusage: "Usage:&r /papermoney [give/reload]"
  message.warning.nopermission: "You do not have permission to use that command."
  message.warning.noconsole: "Command must be used in-game."
  message.warning.nofunds: "Not enough funds."
  message.warning.noplayer: "That player was not found."
  message.warning.notzero: "Amount cannot be zero."
  message.warning.toolittle: "Minimum withdraw allowed is %s."
  message.warning.toofast: "Doing that too fast, try again in &r%s&4 seconds."
  message.info.deposited: "Amount Deposited."
  message.info.balance: "Current Balance:&a %s"
  message.info.inventoryfull: "Inventory Full. Dropped Bank Note at your location."
  message.info.withdrew: "%s withdrew as bank note."
  message.info.given: "You were given a bank note in the amount of&a %s"
  message.info.gave: "Gave [Bank Note : &a%s&2] to&a %s"
  message.info.configreloaded: "Config Reloaded."
  item.name: "&1Bank Note:&2 %s"
  item.lore: "&2&lUse &n/deposit&r&2&l while holding."
  console.disabled: "Plugin Disabled!"
  console.novault: "Disabled due to no Vault dependency found!"
